PokeCry_Text_Articuno:
	.string "Gyaoo!$"

PokeCry_Text_Zapdos:
	.string "Gyaoo!$"

PokeCry_Text_Moltres:
	.string "Gyaoo!$"

PokeCry_Text_Mewtwo:
	.string "Mew!$"

PokeCry_Text_Raikou:
	.string "Rararaiiiii!$"

PokeCry_Text_Entei:
	.string "Enteiiiii!$"

PokeCry_Text_Suicune:
	.string "Susuiiiii!$"

PokeCry_Text_Lugia:
	.string "Gyaaas!$"

PokeCry_Text_Hooh:
	.string "Shaoooh!$"

PokeCry_Text_Celebi:
	.string "Lululalala!$"

PokeCry_Text_Uxie:
	.string "Kyouuuun!$"

PokeCry_Text_Mesprit:
	.string "Kyauun.$"

PokeCry_Text_Azelf:
	.string "Kyuuun…$"

PokeCry_Text_Dialga:
	.string "Gugyugubah!$"

PokeCry_Text_Palkia:
	.string "Gagyagyaah!$"

PokeCry_Text_Heatran:
	.string "Gwogobo gwobobobo!$"

PokeCry_Text_Cresselia:
	.string "Lunaaan…$"

PokeCry_Text_Regigigas:
	.string "…Zut zutt!$"

PokeCry_Text_Giratina:
	.string "Giygogagohgwooh!$"

PokeCry_Text_Darkrai:
	.string "…\n"
	.string "…$"

PokeCry_Text_Shaymin:
	.string "Kyuu uuhn.$"

PokeCry_Text_Arceus:
	.string "Dodogyuuun!$"

PokeCry_Text_Reshiram:
	.string "Preeeeaah!$"

PokeCry_Text_Zekrom:
	.string "Bazzazzazzash!$"

PokeCry_Text_Kyurem:
	.string "Haaahraaan!$"

PokeCry_Text_BKyurem:
	.string "Bazzakyurom!$"

PokeCry_Text_WKyurem:
	.string "Preeeahkyurom!$"
