SpecialBattle_Text_Intro_MysteryRival1:
	.string "Well, you're new. My name is BLANK. My\n"
	.string "friends online call me BLANK2.\p"
	.string "And you are...?\p"
	.string "Oh, okay! Your name is {PLAYER}!\n"
	.string "It's nice to meet you!\p"
	.string "I was in my room playing an MMO game,\n"
	.string "and suddenly, I was pulled in this world.\p"
	.string "I'm still trying to learn this Trainer\n"
	.string "thing, yeah? So I'd like to have a\n"
	.string "battle with you.\p"
	.string "Here I go!$"

SpecialBattle_Text_MysteryRival1Defeated:
	.string "Wow! You're amazing!$"

SpecialBattle_Text_MysteryRival1PostBattle:
	.string "I heard there were five people in this\n"
	.string "region. I'd like to find them.\p"
	.string "Three are people I know, two of which, I\n"
	.string "quite dislike a lot. I need to get to the\n"
	.string "bottom of this.\p"
	.string "So far, I'm one of them.\p"
	.string "But first, I need to get the hang of\n"
	.string "this trainer thing. I'm enjoying it.\p"
	.string "I'll see you soon, {PLAYER}! Again, it's\n"
	.string "nice to meet you.$"